# Generated by Django 5.2.9 on 2026-03-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(db_column='id_alerta', primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('id_medicion', models.ForeignKey(db_column='id_medicion', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mediciones.medicion')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
    ]
