# Generated by Django 5.2.9 on 2026-03-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='prioridad',
            field=models.CharField(default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='id_medicion',
            field=models.ForeignKey(blank=True, db_column='id_medicion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mediciones.medicion'),
        ),
    ]
