# Generated by Django 5.2.9 on 2026-03-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(db_column='id_sensor', primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('id_cultivo', models.ForeignKey(db_column='id_cultivo', on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='cultivos.cultivo')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
    ]
