# Generated by Django 5.2.9 on 2026-03-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id_finca', models.AutoField(db_column='id_finca', primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tamaño_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'finca',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_cultivo', models.AutoField(db_column='id_cultivo', primary_key=True, serialize=False)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('fecha_siembra', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('id_finca', models.ForeignKey(db_column='id_finca', on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='cultivos.finca')),
            ],
            options={
                'db_table': 'cultivo',
            },
        ),
        migrations.CreateModel(
            name='HistorialRiego',
            fields=[
                ('id_riego', models.AutoField(db_column='id_riego', primary_key=True, serialize=False)),
                ('fecha_riego', models.DateField()),
                ('cantidad_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cultivo', models.ForeignKey(db_column='id_cultivo', on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='cultivos.cultivo')),
            ],
            options={
                'db_table': 'historial_riego',
            },
        ),
    ]
