# Generated by Django 5.2.9 on 2026-03-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
