# Generated by Django 5.2.9 on 2026-03-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(db_column='id_medicion', primary_key=True, serialize=False)),
                ('valor_humedad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('id_sensor', models.ForeignKey(db_column='id_sensor', on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sensores.sensor')),
            ],
            options={
                'db_table': 'medicion',
            },
        ),
    ]
