# Generated by Django 5.2.9 on 2026-03-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Agricultor', 'Agricultor')], default='Agricultor', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
